
# Reproduction stage summary

We began the analysis of performance of machine learning algorithms on MIMIC-III database by trying to reproduce the results from an article called *Benchmarking deep learning models on large healthcare datasets*. Unfortunately as the authors of this article used quite a suboptimal method for data extraction which was to connect to database instead of using the csv files that were created earlier, the data preparation process took too many hours and we were not able to reproduce it. Instead we focused on another article focusing on mortality prediction problem on data from MIMIC-III database called *Reproducibility in critical care: a mortality prediction case study*. The authors of this article focused on reproducibility problem, reproducing datasets for 38 experiments. The code they provided looked well written however we were not able to run it without making adjustments. The first problem that we obtained is quite common and it is that the function used for imputation was no longer available. We were able to overcome it by changing the function to SimpleImputer from sklearn, and adjusting the input. The other encountered problems were not as easy to overcome and varied depending on the environment. Not only we had to change the code in the main file, but also in additional files. After adjusting the files, so that the errors would not occur, we were able to run the code and get the  results. However the results that we obtained were slightly but visibly different than the authors’ results. The most explainable reason is that the change of the impute function caused these differences. 
